### ISSUE TITLE
Move to Nextcloud org

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/vue-richtext#747]
Since this is used in quite some places now and becoming more nextcloud specific with #743 I guess we should move it to the nextcloud org.

- [x] Move the repo
- [x] Put brach protection on
- [x] Enable dependabot auto merge action
- [x] Publish new release to `@nextcloud` npm (with automation)
- [ ] publish new release to github package registry.

**Comment by nickvergessen** [comment]
Jup 🚀

**Comment by max-nextcloud** [comment]
@juliushaertl I was able to release 2.0.1 to npms @nextcloud/vue-richtext just fine. So i assume the last item  is also done. Please reopen and clarify if i am mistaken.

**Comment by max-nextcloud** [comment]
https://github.com/nextcloud/vue-richtext/actions/runs/3058068286 looks like the publishing to github package registry does not work yet.
Reopened the issue.

**Comment by nickvergessen** [comment]
Updating in talk worked https://github.com/nextcloud/spreed/pull/7925
